const axios = require('axios');

const GITHUB_API = 'https://api.github.com';

const getHeaders = () => {
  const headers = {
    Accept: 'application/vnd.github.v3+json'
  };

  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  }

  return headers;
};

const getAuthenticatedHeaders = () => {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is required for GitHub Pull Request operations');
  }

  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github.v3+json'
  };
};

const parseRepoUrl = (repoUrl) => {
  const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
  if (!match) throw new Error('Invalid GitHub URL');

  return {
    owner: match[1],
    repo: match[2].replace('.git', '')
  };
};

const fetchRepoFiles = async (repoUrl) => {
  const { owner, repo } = parseRepoUrl(repoUrl);
  const headers = getHeaders();

  const repoInfo = await axios.get(
    `${GITHUB_API}/repos/${owner}/${repo}`,
    { headers }
  );

  const branch = repoInfo.data.default_branch;

  const treeRes = await axios.get(
    `${GITHUB_API}/repos/${owner}/${repo}/git/trees/${branch}?recursive=1`,
    { headers }
  );

  const files = treeRes.data.tree.filter(f => f.type === 'blob');

  const importantExtensions = [
    '.js',
    '.ts',
    '.py',
    '.java',
    '.go',
    '.json',
    '.env.example',
    '.md'
  ];

  const importantFiles = files
    .filter(f => importantExtensions.some(ext => f.path.endsWith(ext)))
    .slice(0, 30);

  const fileContents = await Promise.all(
    importantFiles.map(async (file) => {
      try {
        const res = await axios.get(
          `${GITHUB_API}/repos/${owner}/${repo}/contents/${file.path}`,
          { headers }
        );

        const content = Buffer
          .from(res.data.content, 'base64')
          .toString('utf-8');

        return {
          path: file.path,
          content,
          sha: res.data.sha
        };
      } catch {
        return {
          path: file.path,
          content: '',
          sha: null
        };
      }
    })
  );

  return {
    owner,
    repo,
    branch,
    files: fileContents
  };
};

const createFixPR = async (
  repoUrl,
  filePath,
  fixedCode,
  bugDescription
) => {
  const { owner, repo } = parseRepoUrl(repoUrl);
  const headers = getAuthenticatedHeaders();

  // Step 1: Get authenticated GitHub username
  const botUser = await axios.get(
    `${GITHUB_API}/user`,
    { headers }
  );

  const botUsername = botUser.data.login;

  // Step 2: Fork the repository
  await axios.post(
    `${GITHUB_API}/repos/${owner}/${repo}/forks`,
    {},
    { headers }
  );

  // Step 3: Wait for fork to be ready
  await new Promise(resolve => setTimeout(resolve, 5000));

  // Step 4: Get default branch from original repository
  const repoInfo = await axios.get(
    `${GITHUB_API}/repos/${owner}/${repo}`,
    { headers }
  );

  const baseBranch = repoInfo.data.default_branch;

  // Step 5: Get latest SHA from fork
  const forkBranchRes = await axios.get(
    `${GITHUB_API}/repos/${botUsername}/${repo}/git/ref/heads/${baseBranch}`,
    { headers }
  );

  const baseSha = forkBranchRes.data.object.sha;

  // Step 6: Create new branch on fork
  const newBranch = `repomedic-fix-${Date.now()}`;

  await axios.post(
    `${GITHUB_API}/repos/${botUsername}/${repo}/git/refs`,
    {
      ref: `refs/heads/${newBranch}`,
      sha: baseSha
    },
    { headers }
  );

  // Step 7: Get current file SHA from fork
  const fileRes = await axios.get(
    `${GITHUB_API}/repos/${botUsername}/${repo}/contents/${filePath}`,
    {
      headers,
      params: { ref: baseBranch }
    }
  );

  const fileSha = fileRes.data.sha;

  // Step 8: Commit fixed code
  const encodedContent = Buffer
    .from(fixedCode)
    .toString('base64');

  await axios.put(
    `${GITHUB_API}/repos/${botUsername}/${repo}/contents/${filePath}`,
    {
      message: `🔧 RepoMedic Fix: ${bugDescription.slice(0, 70)}`,
      content: encodedContent,
      sha: fileSha,
      branch: newBranch
    },
    { headers }
  );

  // Step 9: Create Pull Request
  const prRes = await axios.post(
    `${GITHUB_API}/repos/${owner}/${repo}/pulls`,
    {
      title: `🔧 RepoMedic: Fix - ${bugDescription.slice(0, 60)}`,
      body: `## 🤖 RepoMedic AI Fix

**Bug Described:**
${bugDescription}

**Fix Applied to:**
\`${filePath}\`

> This PR was automatically generated by RepoMedic.ai using xAI Grok.`,
      head: `${botUsername}:${newBranch}`,
      base: baseBranch
    },
    { headers }
  );

  return {
    prUrl: prRes.data.html_url,
    prNumber: prRes.data.number,
    branch: newBranch,
    filePath
  };
};

module.exports = {
  fetchRepoFiles,
  parseRepoUrl,
  createFixPR
};