const axios = require('axios');

const GITHUB_API = 'https://api.github.com';

// Parse owner and repo from URL
const parseRepoUrl = (repoUrl) => {
  const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
  if (!match) throw new Error('Invalid GitHub URL');
  return { owner: match[1], repo: match[2].replace('.git', '') };
};

// Fetch repo tree (all files)
const fetchRepoFiles = async (repoUrl) => {
  const { owner, repo } = parseRepoUrl(repoUrl);
  const headers = { Authorization: `token ${process.env.GITHUB_TOKEN}` };

  // Get default branch
  const repoInfo = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}`, { headers });
  const branch = repoInfo.data.default_branch;

  // Get full file tree
  const treeRes = await axios.get(
    `${GITHUB_API}/repos/${owner}/${repo}/git/trees/${branch}?recursive=1`,
    { headers }
  );

  const files = treeRes.data.tree.filter(f => f.type === 'blob');

  // Fetch content of important files (limit to avoid rate limits)
  const importantExtensions = ['.js', '.ts', '.py', '.java', '.go', '.json', '.env.example', '.md'];
  const importantFiles = files
    .filter(f => importantExtensions.some(ext => f.path.endsWith(ext)))
    .slice(0, 30);

  const fileContents = await Promise.all(
    importantFiles.map(async (file) => {
      try {
        const res = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}/contents/${file.path}`, { headers });
        const content = Buffer.from(res.data.content, 'base64').toString('utf-8');
        return { path: file.path, content, sha: res.data.sha };
      } catch {
        return { path: file.path, content: '', sha: null };
      }
    })
  );

  return { owner, repo, branch, files: fileContents };
};

// Create a PR with the fix applied
const createFixPR = async (repoUrl, filePath, fixedCode, bugDescription) => {
  const { owner, repo } = parseRepoUrl(repoUrl);
  const headers = { 
    Authorization: `token ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github.v3+json'
  };

  // Step 1: Get default branch + its SHA
  const repoInfo = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}`, { headers });
  const baseBranch = repoInfo.data.default_branch;

  const branchRes = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`, { headers });
  const baseSha = branchRes.data.object.sha;

  // Step 2: Create new branch
  const newBranch = `repomedic-fix-${Date.now()}`;
  await axios.post(`${GITHUB_API}/repos/${owner}/${repo}/git/refs`, {
    ref: `refs/heads/${newBranch}`,
    sha: baseSha
  }, { headers });

  // Step 3: Get current file SHA (needed to update it)
  const fileRes = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`, {
    headers,
    params: { ref: baseBranch }
  });
  const fileSha = fileRes.data.sha;

  // Step 4: Commit the fixed code to the new branch
  const encodedContent = Buffer.from(fixedCode).toString('base64');
  await axios.put(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`, {
    message: `🔧 RepoMedic Fix: ${bugDescription.slice(0, 70)}`,
    content: encodedContent,
    sha: fileSha,
    branch: newBranch
  }, { headers });

  // Step 5: Open Pull Request
  const prRes = await axios.post(`${GITHUB_API}/repos/${owner}/${repo}/pulls`, {
    title: `🔧 RepoMedic: Fix - ${bugDescription.slice(0, 60)}`,
    body: `## 🤖 RepoMedic AI Fix\n\n**Bug Described:**\n${bugDescription}\n\n**Fix Applied to:** \`${filePath}\`\n\n> This PR was automatically generated by [RepoMedic.ai](https://repomedic-ai.vercel.app) using IBM BOB + Groq AI.`,
    head: newBranch,
    base: baseBranch
  }, { headers });

  return {
    prUrl: prRes.data.html_url,
    prNumber: prRes.data.number,
    branch: newBranch,
    filePath
  };
};

module.exports = { fetchRepoFiles, parseRepoUrl, createFixPR };